### ISSUE TITLE
Did you PR this to laravel/framework?

### ISSUE THREAD

**Issue by it-can** [vemcogroup/laravel-redis#2]
Did you PR this to laravel/framework already?

**Comment by danijelk** [comment]
> Did you PR this to laravel/framework already?

yes, and yes :)

https://twitter.com/taylorotwell/status/1294267460833685506
https://github.com/laravel/framework/pull/31262

**Comment by it-can** [comment]
Mmm maybe try again? It seems the testsuite works correct now..
Also this bug could be fixed by your code? 

https://github.com/laravel/framework/issues/36337

**Comment by it-can** [comment]
@danijelk this PR is now merged... adding support for compression and serializer when using locking... Your code is a nice extra I think?

https://github.com/laravel/framework/pull/36412

**Comment by danijelk** [comment]
> @danijelk this PR is now merged... adding support for compression and serializer when using locking... Your code is a nice extra I think?
> 
> [laravel/framework#36412](https://github.com/laravel/framework/pull/36412)

Glad to finally see progress so many months later. But seems to be only working for lock?, so hopefully someone will open up for regular usage as well

**Comment by it-can** [comment]
> > @danijelk this PR is now merged... adding support for compression and serializer when using locking... Your code is a nice extra I think?
> > [laravel/framework#36412](https://github.com/laravel/framework/pull/36412)
> 
> Glad to finally see progress so many months later. But seems to be only working for lock?, so hopefully someone will open up for regular usage as well

yeah only locking...

**Comment by TheLevti** [comment]
I am working on a pull request to add the missing configs. I will tag you there as I have some questions to your original pull request that got closed for some unknown reason.

**Comment by danijelk** [comment]
> I am working on a pull request to add the missing configs. I will tag you there as I have some questions to your original pull request that got closed for some unknown reason.

Sounds great, will do my best to remember what we tried to fix :)

**Comment by TheLevti** [comment]
https://github.com/laravel/framework/pull/36791

**Comment by TheLevti** [comment]
What I did not understand is why you added these zscore and executeRaw changes (https://github.com/laravel/framework/pull/31262/files). Are they related to adding support for serialization/compression configs?

**Comment by danijelk** [comment]
> What I did not understand is why you added these zscore and executeRaw changes (https://github.com/laravel/framework/pull/31262/files). Are they related to adding support for serialization/compression configs?

Great work with the PR, hopefully it gets in, looks cleaner than what was done on the 6.x branch.

The zscore method was added as it was simply missing (like zadd and exists), there was a spot where it checks if method exist and uses it, else it went to some lua script. And if it's not defined it doesn't go through the executeRaw() which was the only way to apply compression/serialisation at that time.
